name: Run Tests

on:
 - 'push'
 - 'pull_request'
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: sudo apt-get install lcov
    - name: make
      run: g++ --std=c++17 --coverage main.cc -lz -llzma
    - name: run
      run: ./a.out
    - name: Capture LCOV
      run: lcov --capture --no-external --directory . --output-file lcov.info
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: lcov.info

